language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
sudo: required
services:
- docker
script:
- >
  wget -O- bit.ly/ansibletest | env
  DOCKER_IMAGES="centos:6 centos:7 ubuntu:12.04 ubuntu:16.04
  fedora:20 fedora:25 debian:7 debian:stretch"
  ANSIBLE_VERSIONS="1.4"
  sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      secure: v2U+R6bxSApkxmGYw4+4zKXMuYCv5uARF2qEPxB8ZSpZ9qP4bsiFmZ2lgj9h9VZDuMBa6+NvlsHSjEFtJJ1HB6V9BsnX9MXtyRwkeFuXf8PY6biDbuTJm3cIjiEj6+CrUKHaCN6pIauHztHEcRXLq2MYuCUQALT6UlTx/r/4e/pvP5lco4MUmy1aRXJji736tOn3pjr8i3kC26JYiE8ta9kgahjqDPhq5cYKfg7DmwE1ieSzcSUElEY7+8ht1gYNd+5h04j8hUd7eOaalxszF19SSv18DSDAs6clGYQFQ9QvlnZ+Ipu31yLA1q4WIC1Wo55w/Iwbbm2RVCsoAU9iz8Sn7wRNT66kB/dWImeWE9GiSxqF+t2asXdpxqDO0bdWpwqEEY/ZFzPpv0D0KhS719LZLLSYAAwP0KkNUFeaiCYij7PSB+ingO0K/SSyiRdd1sDQfHUPwUPE0M2XnE29AjtrcbC/YU0S/tM6fwxjwDcyQdUA9ptTCH+8eka4etpjlQANxOnXb2HCBXB42JWWsgTBcDdMVnQtV61c+UY4sC0E3fTdvGl+3KAYIql3h8wpAKOP4+11v/3hhQA8bvIdYt53v/weUqne/AO2NsSelpT1+zLEy4ZjgCAaxZIo+fdXmOfIqwmPN34k7HPZblC4WGeLwTL7MQPwMD/fWi0LI2g=
